# Generated by Django 5.2.4 on 2025-07-22 16:06

from decimal import Decimal

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('married', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.person')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Contributor', max_length=100)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdjdatalog.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(through='testdjdatalog.ProjectAssignment', to='testdjdatalog.employee'),
        ),
        migrations.CreateModel(
            name='HasAuthorityStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='ManagerOfStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='MemberOfStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='ParentOfStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='MarriedToStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='IsManagerStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='IsAdminStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='PersonWorksForStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.company')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.person')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='CanAccessStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='WorksForStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.company')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
        migrations.CreateModel(
            name='WorksOnStorage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testdjdatalog.employee')),
            ],
            options={
                'abstract': False,
                'unique_together': {('subject', 'object')},
            },
        ),
    ]
